ingenius/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','reg.views.home',name='home'),
    url(r'^login/?$','reg.views.login_user',name='login'),
    url(r'^logout/?$','reg.views.logout_user',name='logout'),
    url(r'^register/?$','reg.views.register',name='register'),
    url(r'^breakfast/?$','reg.views.breakfast',name='breakfast'),
    url(r'^lunch/?$','reg.views.lunch',name='lunch'),
    url(r'^dinner/?$','reg.views.dinner',name='dinner'),
    url(r'^snacks_evening/?$','reg.views.snacks_evening',name='snacks_evening'),
    url(r'^snacks_midnight/?$','reg.views.snacks_midnight',name='snacks_midnight'),
    url(r'^check_in/?$','reg.views.check_in',name='check_in'),
    url(r'^stats/?$','reg.views.stats',name='stats'),
    url(r'^dashboard/?$','reg.views.dashboard',name='dashboard'),
]

reg/forms.py
from django import forms

class LoginForm(forms.Form):
	username 	= forms.CharField(label="Username",max_length=50,required=True)
	password	= forms.CharField(label="Password",max_length=50,required=True,
		widget=forms.PasswordInput)

class RegForm(forms.Form):
	GENDER_CHOICES = (
		('M', 'Male'),
		('F', 'Female'),
	)
	pid = forms.CharField(label="Participant ID or Mobile Number",\
		max_length=10,required=True)
	noc_submitted = forms.BooleanField(label="NOC Submitted", required=False)
	barcode	= forms.CharField(label="Barcode",max_length=100,required=False)

	def __init__(self, *args, **kwargs):
		from django.forms.widgets import HiddenInput
		show_noc = kwargs.pop('show_noc',None)
		hide_barcode = kwargs.pop('hide_barcode',None)
		super(RegForm, self).__init__(*args, **kwargs)
		if not show_noc:
			self.fields['noc_submitted'].widget = HiddenInput()
		if hide_barcode:
			self.fields['barcode'].widget = HiddenInput()

class CheckInForm(forms.Form):
	barcode = forms.CharField(max_length=100, required=True)

class LunchForm(forms.Form):
	barcode = forms.CharField(max_length=50, required=True)

class BreakfastForm(forms.Form):
	barcode = forms.CharField(max_length=50, required=True)

class DinnerForm(forms.Form):
	barcode = forms.CharField(max_length=50, required=True)

class SnacksEveningForm(forms.Form):
	barcode = forms.CharField(max_length=50, required=True)	

class SnacksMidnightForm(forms.Form):
	barcode = forms.CharField(max_length=50, required=True)	

templates/base.html
{% load staticfiles %}

<!DOCTYPE HTML>
<!-- skel-baseline v3.0.0 | (c) n33 | skel.io | MIT licensed -->
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>

		{% block extrahead %}
		{% endblock %}
	</head>
	<body id="top">

		<!-- Header -->
			<header id="header">
				<h1><a href="/">inGenius 2018</a></h1>
				{% if request.user.is_authenticated %}
				<a href="/logout">{{ request.user.username }} (Logout)</a>
				{% else %}
				<a href="/login">Login</a>
				{% endif %}
				<a href="#nav">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="/">Home</a></li>
					<li><a href="/register">Registration</a></li>
					<li><a href="/lunch">Lunch (Day 1)</a></li>
					<li><a href="/snacks_evening">Snacks (Evening)</a></li>
					<li><a href="/dinner">Dinner (Day 1)</a></li>
					<li><a href="/snacks_midnight">Snacks (MidNight)</a></li>
					<li><a href="/breakfast">Breakfast (Day 2)</a></li>
					<li><a href="/check_in">Check-in/out</a></li>
					<li><a href="/stats">Stats</a></li>
				</ul>
			</nav>


		<!-- Main -->

			{% block content %}
			{% endblock %}

		<!-- Footer -->
			<footer id="footer">
				<div class="copyright">
					&copy; inGenius 2018. All rights reserved.
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'js/skel.min.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/breakfast.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Breakfast | inGenius 2017</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
        <h3>Breakfast (Day 2)</h3>
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Submit" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>
    <script>
		$(document).ready(function (){
			$('#id_barcode').focus();
		});
		</script>
	    {% endblock %}

templates/checkin.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Check-in / Check-out | inGenius 2017</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
					<h3>Check-in / Check-out</h3>
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Check-in / Check-out" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>

		<script>
		$(document).ready(function (){
			$('#id_barcode').focus();
		});
		</script>

	    {% endblock %}

templates/dashboard.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
  <title>Dashboard | inGenius 2017</title>
  <meta charset="utf-8">
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.countdown.min.js' %}"></script>

  <style type="text/css">
  body {
    font-family: 'Roboto', Helvetica, sans-serif;
    color: #000;
  }
  #countdown {
    margin-top: 20px;
    font-size: 100px;
    font-weight: 300;
    text-align: center;
  }
  .triggers {
    float:right;
    color: rgba(0, 0, 0, 0.5);
  }
  a, a:active, a:visited, a:focus {
    text-decoration: none;
    cursor: pointer;
    color: inherit;
  }
  </style>
</head>
<body>
  <div class="container">
    <div class="triggers">
      <a href="#" class="start">Resume</a>
      <a href="#" class="stop">Pause</a>
    </div>
    <div id="countdown"></div>
  </div>

  <script type="text/javascript">
  var ctdn = $('#countdown');
  ctdn.countdown("2015/10/01 12:00:00",function(event){
    $(this).html(event.strftime('%H:%M:%S'));
  });
  $('.start').click(function(){
    ctdn.countdown('start');
  });
  $('.stop').click(function(){
    ctdn.countdown('stop');
  });
  </script>
</body>
</html>

templates/dinner.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Dinner | inGenius 2017</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
        <h3>Dinner (Day 1)</h3>
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Submit" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>
    <script>
		$(document).ready(function (){
			$('#id_barcode').focus();
		});
		</script>
	    {% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extrahead %}
<title>Home | inGenius 2017</title>
{% endblock %}

{% block content %}
<!-- Banner -->
  <section id="banner">
    <img src="{% static 'images/logo_light.png' %}" width="50%"  alt="inGenius 2015" />
    
    <p style="font-size:22px;">Get. Set. Hack.</p>
    <ul class="actions">
      {% if not request.user.is_authenticated %}
      <li><a href="/login" class="button alt">Login</a></li>
      {% endif %}
    </ul>
  </section>

<!-- Main -->

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Login | inGenius 2017</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Login" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>

	    {% endblock %}

templates/lunch.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Lunch | inGenius 2017</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
        <h3>Lunch (Day 1)</h3>
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Submit" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>
    <script>
		$(document).ready(function (){
			$('#id_barcode').focus();
		});
		</script>
	    {% endblock %}

templates/register.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Registration | inGenius 2018</title>

        <style type="text/css">
        .participant-details {
        	background-color: rgba(0,0,0,0.03);
        }
				.paid {
					color: #286c17;
					font-size: 1.1em;
					font-weight: bold;
				}
				.not-paid {
					color: #ce223b;
					font-size: 1.1em;
					font-weight: bold;
				}
				.change-button {
					pointer: cursor;
					float:right;
				}
        </style>

        {% endblock %}


        {% block content %}

        <div id="main" class="container">
				<h2><a href="{% url 'register' %}">Registration</a></h2>
		    {% if message %}
		    <div class="12u {{ messageclass }}">
		    	{{ message }}
		    </div>
		    {% endif %}

		    <div class="row">
		    <div class="6u 12u(small)">
	    	<div class="row">
		        <form action="" method="POST">
		            {% csrf_token %}
		            {{form.as_p}}
		            <input type="submit" value="Submit" />
		        </form>
		    </div>
		    </div>
		    <div class="6u 12u(small)">
				<div class="row">
			        {% if participant_details %}
			        <div class="box participant-details 12u">
								<div class="row">
					        <h3>Participant details</h3>
									<div class="change-button">
										<a class="button small" href="/admin/reg/participant/{{ participant_details.pid }}/" target="_blank">Change</a>
									</div>
								</div>
								<hr class="minor">
				        <div class="row">
				        	<p class="4u"><strong>Participant ID:</strong> {{ participant_details.participant_id }}</p>
				        	<p class="4u"><strong>Barcode:</strong> {{ participant_details.barcode }}</p>
									{% if participant_details.paid == 'Yes' %}
									<p class="4u"><strong>Paid:</strong> <span class="paid">{{ participant_details.paid }}</span></p>
									{% else %}
									<p class="4u"><strong>Paid:</strong> <span class="not-paid">{{ participant_details.paid }}</span></p>
									{% endif %}
        				</div>
								<div class="row">
									<p class="12u"><strong>Team checked-in:</strong> {{ participant_details.team_checked_in }}</p>
								</div>
								<hr class="minor">
				        <div class="row">
					        <p class="6u"><strong>Name:</strong> {{ participant_details.name }}</p>
					        <p class="6u"><strong>Phone:</strong> {{ participant_details.phone }}</p>
					    	</div>
				        <div class="row">
				        	<p class="6u"><strong>Team name:</strong> {{ participant_details.team_name }}</p>
				        	<p class="6u"><strong>Gender:</strong> {{ participant_details.gender }}</p>
				        </div>
								<div class="row">
									<p class="12u"><strong>College:</strong> {{ participant_details.college }}</p>
								</div>
								<div class="row">
				        	<p class="12u"><strong>Email id:</strong> {{ participant_details.email }}</p>
				        </div>
								<hr class="minor">
				        <div class="row">
				        	<p class="6u"><strong>Checked-in:</strong> {{ participant_details.checked_in }}</p>
				        	<p class="6u"><strong>Registered:</strong> {{ participant_details.registered }}</p>
				        </div>
			        </div>
				    </div>
			        {% endif %}
			    </div>
		    </div>
				<div class="push"></div>
		    </div>

		    {% if form_type == 1 %}

	    	<script>
	    	$(document).ready(function (){
	    		$('#id_pid').focus();
	    	});
	    	</script>

	    	{% endif %}

	    	{% if form_type == 2 %}

	    	<script>
	    	$(document).ready(function (){
	    		$('#id_barcode').focus();
	    	});
	    	</script>

	    	{% endif %}

    	</div>

	    {% endblock %}

templates/snacksevening.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Snacks Evening | inGenius 2018</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
        <h3>Snacks Evening (DAY 1)</h3>
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Submit" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>
    <script>
		$(document).ready(function (){
			$('#id_barcode').focus();
		});
		</script>
	    {% endblock %}

templates/snacksmidnight.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Snacks Midnight | inGenius 2018</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">

	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}

	    <div class="row">
	    <div class="4u$ -4u 12u(small)">
        <h3>Snacks Midnight</h3>
	        <form action="" method="POST">
	            {% csrf_token %}
	            {{form.as_p}}
	            <input type="submit" value="Submit" />
	        </form>
	    </div>
	    </div>
			<div class="push"></div>
		</div>
    <script>
		$(document).ready(function (){
			$('#id_barcode').focus();
		});
		</script>
	    {% endblock %}

templates/stats.html
{% extends 'base.html' %}

{% load staticfiles %}

		{% block extrahead %}

		<title>Stats | inGenius 2017</title>

    {% endblock %}


    {% block content %}
		<div id="main" class="container">
			<h2>Stats</h2>
			<hr class="major">
	    {% if message %}
	    <div class="12u box {{ messageclass }}">
	    	{{ message }}
	    </div>
	    {% endif %}
			<div class="row">
				<div class="6u stat-card-wide stat-card">
					<h2>Teams</h2>
					<p class="">{{ teams }}</p>
				</div>
				<div class="6u stat-card-wide stat-card">
					<h2>Participants</h2>
					<p class="">{{ participants }}</p>
				</div>
			</div>
			<div class="row">
				<div class="4u stat-card">
					<h3>Registered</h3>
					<p class="">{{ registered }}</p>
				</div>
				<div class="4u stat-card">
					<h3>Checked-in</h3>
					<p class="">{{ checked_in }}</p>
				</div>
				<div class="4u stat-card">
					<h3>Paid</h3>
					<p class="">{{ paid }}</p>
				</div>
			</div>
			<div class="row">
				<div class="4u stat-card">
					<h3>Had Lunch</h3>
					<p class="">{{ had_lunch }}</p>
				</div>
				<div class="4u stat-card">
					<h3>Had Dinner</h3>
					<p class="">{{ had_dinner }}</p>
				</div>
				<div class="4u stat-card">
					<h3>Had Breakfast</h3>
					<p class="">{{ had_breakfast }}</p>
				</div>
			</div>
			<div class="push"></div>
		</div>
	  {% endblock %}